language: erlang # wither art thou, Go?

install:
 - hg clone -r weekly https://code.google.com/p/go $HOME/go
 - cd $HOME/go/src && ./make.bash
 - mkdir -p $HOME/src || true
 - mkdir -p $HOME/bin || true
 - mkdir -p $HOME/pkg || true
 - export GOPATH=$HOME
 - export PATH=$PATH:$HOME/go/bin
 - ln -s $HOME/builds/mattn/go-sqlite3 $HOME/src/go-sqlite3
 - go get -v github.com/mattn/go-sqlite3

script:
 - cd $HOME/src/go-sqlite3 && go build -v .
 - cd $HOME/src/go-sqlite3 && go test -v .
